### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by drzax** [quantsquills/governance#1]
It would be nice to have some rudimentary logo—mostly so we can have an avatar on GitHub, but I'm sure it would be handy in other ways too.

**Comment by drzax** [comment]
Here are a few options from 5 mins of mucking around.

![image](https://user-images.githubusercontent.com/596563/29599752-31419382-8815-11e7-883b-2d270949fe7a.png)
![image](https://user-images.githubusercontent.com/596563/29599763-419d9942-8815-11e7-9854-1fcf264a8cea.png)
![image](https://user-images.githubusercontent.com/596563/29599765-4545cba0-8815-11e7-885e-7a202c9450f1.png)

**Comment by antmandan** [comment]
I like the middle one most. Nice colour choice.

**Comment by drzax** [comment]
Done! I'll leave it at that for now until some professional designer wants to volunteer their time to improve it.
