### ISSUE TITLE
Create spreadsheet to help allocate volunteers for each event

### ISSUE THREAD

**Issue by drzax** [quantsquills/governance#13]
- organising/booking speakers
- filming or recording of the event
- photography
- live tweeting
- stocking drinks
- packing up

**Comment by rosieryan** [comment]
Here's a link to the spreadsheet: https://docs.google.com/spreadsheets/d/1JpGmxtKdzMc1i6m8BmeldSxFtrywFyKLsGlAMNrQwwk/edit#gid=0
