### ISSUE TITLE
Newsletter proposal

### ISSUE THREAD

**Issue by drzax** [quantsquills/governance#32]
Below is a proposal for a new Hacks/Hackers Brisbane email newsletter from @kcassowary as discussed at the AGM. I've copied her proposal here for further discussion. 
__________________________

## How:

At this stage, I'm just thinking of using MailChimp - but let me know if there's any issue with that/a better option. Is there a central H/H email I could be using for it? Otherwise I'll just set up a "personal" one (ie, something like katie.hhbne@gmail etc,) just for the newsletter distribution.

Rosie has collected a bunch of emails to kick it off with, from people who attended the November meetup - thank you, Rosie!

We can also push out links on FB and Twitter, if people want to sign up. My hope is that the newsletter will attract more people/diverse crowd to the Wed talks. But having said that, I think it could also be a good resource for people who aren't able to make it from week to week.

## When:

I think the H/H newsletter can be sent out the Monday before a meetup, and the Friday after a meetup. One would preview what's coming up, and the other a re-cap.

I can kick it off on the Monday before our February meetup.

### What's coming up this month
- What's the topic and who's the speaker
- This section could also include "background" reading on the topic/speaker, or links suggested by the speaker

### Recap on last month's presentation
- Key takeaways from the speaker
- Any additional reading/links

### What we're into it - best reads/listens/watches
- A list of maybe 5 things, which could come from anywhere, but should focus on digital storytelling as a practice or are amazing examples of it
- So best reads, a new podcast recommendations, an excellent new thing that's streaming

### Place for ads/services/shout-outs
-    The goal of this section is to foster a community noticeboard, of sorts
-    Brisbane based, digital focus? 

### Something about Brisbane we want to mention
-    Cool things you didn't know
-    Something new that we want to highlight
-    Ideas: Best books about Brisbane; Best food in the suburbs

### Official stuff for the end
-    What's the bigger group we're part of
-    Sponsors
-    Recommend to a friend/Subscribe
-    Unsubscribe
-    Become a member?
-    Social accounts - FB group page/Meetup page/Twitter 

## Why:
-    To build a community bigger than the group that is able to join us on Wed evenings
-    Be a resource for people who aren't able to make the meetups from week to week
-    The email should think global but act local - so Brisbane and the world should be reflected
-    Attract a diverse audience to Hacks/Hackers Brisbane, and foster cross-industry understanding and collaboration

### Who:

Well, me. I'm keen to write and produce the newsletter, which I'm sure I'll be able to manage.

However, I think we'll all need to pitch in with the suggestion sections (!!). There's only so much media I can consume, but also, the newsletter should be reflective of the group - rather than me and what I like!

**Comment by drzax** [comment]
Thanks for the fantastic proposal. I love it and I'm super keen to help make it happen. A few thoughts below.

**Choice of provider**: I'm in favour of MailChimp. One thing I'd like to give consideration to early is how we archive. To this end, it would be great if we could do most of the authoring in Markdown (Craig Mod has a long video explaining [why Markdown is good for archiving](https://www.youtube.com/watch?v=cyyR-j2eIAs)).  Aside from anything else, I think it's important that Quants & Quills 'owns' the content, in as much as it's not locked into a provider's ecosystem.

**From address:** I can setup an email address — probably something like newsletter@@quantsquills.com and we can just forward it to whoever is running the newsletter!

**When:** My inclination would be to start with monthly and go more frequent once we know we have the capacity. But happy to go with your schedule if you think you can commit to it.

**Content:** I like all your proposed sections, though I'm not sure how I see the Brisbane section working. I wonder if it would be an opportunity to seek new sponsorship, like: _This section brought to you by BNE MKTING_, for example.

**Who:** Brilliant. I reckon if you can write/produce the newsletter with input for specific sections from the rest of us that would work well. I think a presence from all of us would work especially well in the 'what we're into' section. We could all submit a link/whatever to each one.

## Other thoughts

I've been reading through https://newsletterguide.org/ which is very comprehensive. I think it's worth a browse.

### Branding
I wonder if it's worth thinking about a name for the newsletter.

### Design
FWIW, I'm hugely in favour of minimalist design in email newsletters. Something that promotes clarity, is easy to skim and uses clear, direct, simple language (both visual and written). 

### Newsletters I like and why
A lot of my favourite email newsletters a quite personal in tone — I feel like I've got some kind of relationship with the writer. Here are a few of my faves:

- [Dense Discovery](https://www.densediscovery.com/) - I love how open Kai is about his work. It fosters a real and strong relationship with readers.
- [Roden](https://craigmod.com/roden/) - I like pretty much anything Craig Mod writes, but again the personal nature of the way he addresses the audience is great. It seems to genuinely invite participation. It's also lovely writing.
- [Nieman Lab](http://www.niemanlab.org/subscribe/) - Just useful news industry stuff, but I rarely get past the top section.
- [INN's Nerd Alert](https://labs.inn.org/) - The only section I read regularly in this one is the personal recommendations bit, which I think we could do something similar to.

That'll do for now.

**Comment by drzax** [comment]
Aside: This is an interesting read from Craig Mod about [the future of the book](https://www.wired.com/story/future-book-is-here-but-not-what-we-expected/). I think a lot of this translates to journalism pretty neatly.

**Comment by kcassowary** [comment]
Re, _Content: I like all your proposed sections, though I'm not sure how I see the Brisbane section working. I wonder if it would be an opportunity to seek new sponsorship, like: This section brought to you by BNE MKTING, for example._

- I really like this idea, and would be good way to get our own "brand" out, and by extension into different communities

Re, _branding & design:_

- I had actually thought of this myself recently, and wondered if we could rope in a designer friend to help; will think on name. And I agree with minimalism. 

### Newsletters I like and why:

[Ann Friedman](https://www.annfriedman.com/newsletter-archive/) - Ann is a feminist writer and podcast host from the US. I like Ann's voice, mostly. She's positive, eloquent, passionate.  

[Ren LaForme's Tools for Journalism](http://go.pardot.com/webmail/273262/302071543/bb53387ca28f59aba4c0af5de3edfb4851480c74a698b27dc92cba7e08843ebd) - I honestly always read to the bottom. Yes, it's relevant to my industry but the clear headings, dot points, links etc make it easy to scan.

Best of Pocket - This isn't even really a newsletter. But I often use these round-ups to read the best stuff I've missed during the week. The takeaway from this is the simplicity of it.

**Comment by kcassowary** [comment]
Just a quick one: This week I received the first of a new newsletter I had signed up to. It was a MailChimp one - but the font size/formatting on my phone was bad, ie, really small. If anyone has used MailChimp before and is aware of this and has tips to avoid it, I'd appreciate it!

**Comment by drzax** [comment]
As far as I understand it, this is an email design issue and not a
Mailchimp issue—we can use whatever design/code we like with Mailchimp.
However they do, I'm sure, offer some stock/template designs. I would hope
and expect that these all played well with mobile clients.

Email design/dev is a very difficult endeavour.

**Comment by drzax** [comment]
Design inspiration:
* https://us2.campaign-archive.com/?u=ed2d318978b7dc9b30b1f464f&id=5c506ab171

**Comment by drzax** [comment]
I think if we find one we can all agree on in the Campaign Monitor [free templates](https://www.campaignmonitor.com/email-templates/responsive/) gallery then we should just go with that for now and evolve it as necessary.

**Comment by kcassowary** [comment]
So this is Canva for newsletters? And the build happens there, then we distribute via MailChimp?

I would vote [for this one](https://templates.campaignmonitor.com/canvas/design/13-the-blueprint-3#/editor), cause it doesn't rely on pics so much

**Comment by drzax** [comment]
Campaign Monitor is a competitor to MailChimp, but I think that builder can
be used to create a template we could potentially use on any platform.

**Comment by kcassowary** [comment]
[First newsletter](https://mailchi.mp/31e47e6647f2/inside-the-inside-story-of-a-flying-telescope) is sent!

Here's our [signup page](http://eepurl.com/ghECO5), if we want to push it out via the social media...

Thanks @drzax @rosieryan and Jonathan :)

**Comment by drzax** [comment]
Great work, thanks @kcassowary.

**Comment by drzax** [comment]
Potential sponsors:
- https://www.somethingdigital.com.au/

**Comment by drzax** [comment]
I'm closing this issue because it got done (_thanks @kcassowary!_). But it still has quite a bit of useful information and I might open a new, more specific task for email re-design which points here. But I want to prioritise the website first.
