### ISSUE TITLE
Create speaker survey

### ISSUE THREAD

**Issue by drzax** [quantsquills/governance#34]
We should have a standard set of questions we ask of speakers to ensure we have everything we need to make the events as good as possible. I think a good way to do this would be with a pro-forma email which includes a link to a Google Form with all the relevant questions.

> Thank you for agreeing/considering speaking about <topic> at Hacks/Hackers Brisbane on <date>.
> Our events are relatively casual affairs, but we do try to make them as smooth and professionally run as possible.
> In order to make your event the best it can be we need a few details from you. The best way we've found to collect this information is with a [short survey](link). Filling this out should take about 5 minutes and will give us all the information we need to properly promote your event and make sure it runs smoothly on the night.

Proposed questions:
- What is the title of your talk?
- Can you expand on what you'll talk about a little? We're looking for about 150 words on what it's all about that we can use for marketing an event promotion.
- Do you have any imagery we can use to promote your event?

**Comment by drzax** [comment]
I'd like to expand this list of questions—throw in your suggestions in a comment and I'll put it all together.

**Comment by kcassowary** [comment]
Couple of suggestions: 

Do you have any articles/reads/listen etc you'd like to suggest to our newsletter subscribers?
What's your preferred social handle - Twitter, Facebook etc - where people can find you or your work?

**Comment by drzax** [comment]
This form hosting tool looks worth a try. https://tripetto.app/

**Comment by drzax** [comment]
* Will you be using any audio in your presentation?
* Will you need internet access?
* Would you be comfortable with us recording your talk?
  * Video
  * Audio
  * Live-stream

**Comment by drzax** [comment]
Here's a [draft speaker survey](https://docs.google.com/forms/d/e/1FAIpQLScSf6Hprm3sCeHzEUhAYmFYsijDa-Kfi9UlYmfq68UP7J6D2A/viewform). I'd love some feedback.

I tried out Survey Monkey and Tripetto, but in the end Google Forms is the only one to offer a free upload functionality for event images. The only drawback is that it requires a Google login.

**Comment by kcassowary** [comment]
Is there a reason you separated it into 3 pages? Rather than just having all the questions on one page? Or does Google just do that? I know you say it'll take 5 mins, but maybe it's worth adding how many questions there are all up? ie, "Filling this out should take about 5 minutes (there's 10 questions all up) and will give us all the information..." 

Otherwise I think it all looks good.

**Comment by drzax** [comment]
I think the only reason for separating was aesthetics—probably not a good
reason. I like the idea of saying the number of questions (and TBH, I
guessed at the 5minute thing). Will review these suggestions.

**Comment by drzax** [comment]
I'm going to close this issue. It got done, but hasn't been very successful (i.e. nobody used the survey). I still think it would be good to have a checklist of things to get from speakers so we know what we need and why. That might be something for the [knowledge base](https://app.gitbook.com/@quants-and-quills/s/hacks-hackers-brisbane/).
